
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

ARG JAR_FILE=app.jar
COPY ${JAR_FILE} /app/Crm.jar

ENTRYPOINT ["java",
 "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
  "-Dspring.profiles.active=docker-props",
  "-jar","/app/Crm.jar"
  ]
