
name: Gradle Build & Artifact

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew clean assemble --no-daemon

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.sha }}
          path: |
            **/build/libs/*.jar
          if-no-files-found: error
          retention-days: 7
